services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: always
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_appdb
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: strongpassword
      MB_DB_HOST: db
    volumes:
      - ./metabase-data:/metabase-data
    networks:
      - metabase-net

  db:
    image: postgres:16
    container_name: metabase_db
    restart: always
    environment:
      POSTGRES_DB: metabase_appdb
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
    networks:
      - metabase-net

networks:
  metabase-net:
    driver: bridge